#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v19
# autospec commit: 6a4b23bb3e69
#
Name     : mimalloc
Version  : 2.1.7
Release  : 1
URL      : https://github.com/microsoft/mimalloc/archive/v2.1.7/mimalloc-2.1.7.tar.gz
Source0  : https://github.com/microsoft/mimalloc/archive/v2.1.7/mimalloc-2.1.7.tar.gz
Summary  : A compact general purpose allocator with excellent performance
Group    : Development/Tools
License  : MIT
Requires: mimalloc-lib = %{version}-%{release}
Requires: mimalloc-license = %{version}-%{release}
BuildRequires : buildreq-cmake
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
<img align="left" width="100" height="100" src="doc/mimalloc-logo.png"/>
[<img align="right" src="https://dev.azure.com/Daan0324/mimalloc/_apis/build/status/microsoft.mimalloc?branchName=dev"/>](https://dev.azure.com/Daan0324/mimalloc/_build?definitionId=1&_a=summary)

%package dev
Summary: dev components for the mimalloc package.
Group: Development
Requires: mimalloc-lib = %{version}-%{release}
Provides: mimalloc-devel = %{version}-%{release}
Requires: mimalloc = %{version}-%{release}

%description dev
dev components for the mimalloc package.


%package lib
Summary: lib components for the mimalloc package.
Group: Libraries
Requires: mimalloc-license = %{version}-%{release}

%description lib
lib components for the mimalloc package.


%package license
Summary: license components for the mimalloc package.
Group: Default

%description license
license components for the mimalloc package.


%prep
%setup -q -n mimalloc-2.1.7
cd %{_builddir}/mimalloc-2.1.7

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1726702175
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1726702175
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/mimalloc
cp %{_builddir}/mimalloc-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/mimalloc/4e0d5d15ab4f212c645d939f71c319ba648a8cce || :
export GOAMD64=v2
GOAMD64=v2
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)
/usr/lib64/mimalloc-2.1/mimalloc.o

%files dev
%defattr(-,root,root,-)
/usr/include/mimalloc-2.1/mimalloc-new-delete.h
/usr/include/mimalloc-2.1/mimalloc-override.h
/usr/include/mimalloc-2.1/mimalloc.h
/usr/lib64/cmake/mimalloc-2.1/mimalloc-config-version.cmake
/usr/lib64/cmake/mimalloc-2.1/mimalloc-config.cmake
/usr/lib64/cmake/mimalloc-2.1/mimalloc-relwithdebinfo.cmake
/usr/lib64/cmake/mimalloc-2.1/mimalloc.cmake
/usr/lib64/libmimalloc.so
/usr/lib64/pkgconfig/mimalloc.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libmimalloc.so.2
/usr/lib64/libmimalloc.so.2.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mimalloc/4e0d5d15ab4f212c645d939f71c319ba648a8cce
